# Generated by Django 3.2.18 on 2023-03-01 23:54

import app.models.task
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_task_epsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugindatum',
            name='bool_value',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Bool value'),
        ),
        migrations.AlterField(
            model_name='plugindatum',
            name='json_value',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='JSON value'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text="Options that define this preset (same format as in a Task's options).", validators=[app.models.task.validate_task_options], verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='task',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Options that are being used to process this task', validators=[app.models.task.validate_task_options], verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pending_action',
            field=models.IntegerField(blank=True, choices=[(1, 'CANCEL'), (2, 'REMOVE'), (3, 'RESTART'), (4, 'RESIZE'), (5, 'IMPORT'), (6, 'PULL')], db_index=True, help_text='A requested action to be performed on the task. The selected action will be performed by the worker at the next iteration.', null=True, verbose_name='Pending Action'),
        ),
        migrations.AlterField(
            model_name='task',
            name='potree_scene',
            field=models.JSONField(blank=True, default=dict, help_text='Serialized potree scene information used to save/load measurements and camera view angle', verbose_name='Potree Scene'),
        ),
    ]
