# Generated by Django 3.2.18 on 2023-03-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_delete_imageupload'),
        ('app', '0034_merge_0033_auto_20230301_2354_0033_auto_20230307_1532'),
    ]

    operations = [
    ]
