# Generated by Django 3.2.18 on 2023-05-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_merge_20230324_0147'),
        ('app', '0035_task_orthophoto_bands'),
    ]

    operations = [
    ]
