# Generated by Django 3.2.18 on 2023-03-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeodm', '0009_auto_20210610_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingnode',
            name='available_options',
            field=models.JSONField(default=dict, help_text='Description of the options that can be used for processing', verbose_name='Available Options'),
        ),
    ]
